# Generated by Django 4.2.2 on 2023-06-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_client_emailsubscriber_slot_alter_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
