# Generated by Django 4.2.2 on 2023-06-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechBlog', '0002_tag_techpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='techpost',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
