# Generated by Django 4.2.2 on 2023-06-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechBlog', '0003_techpost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
