# Generated by Django 4.2.2 on 2023-06-26 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TechBlog', '0005_remove_techpost_likes_techpost_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TechBlog.blogcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechBlog.techpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techblog_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
