# Generated by Django 4.2.2 on 2023-07-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechBlog', '0012_remove_replies_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replies',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Replies',
        ),
    ]
