# Generated by Django 4.2.2 on 2023-07-16 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TechBlog', '0014_blogcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogComment',
            new_name='TechBlogComment',
        ),
    ]
